apiVersion: v1
kind: Namespace
metadata:
  name: agentgateway-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kgateway-crds
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/kgateway-dev/charts/kgateway-crds
  ref:
    tag: "2.3.0-main"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway-crds
  namespace: flux-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kgateway-crds
  install:
    crds: CreateReplace
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kgateway
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/kgateway-dev/charts/kgateway
  ref:
    tag: "2.3.0-main"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kgateway
  namespace: agentgateway-system
spec:
  interval: 1h
  targetNamespace: agentgateway-system
  dependsOn:
    - name: kgateway-crds
      namespace: flux-system
  chartRef:
    kind: OCIRepository
    name: kgateway
    namespace: flux-system
  install:
    createNamespace: true
