apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  annotations:
    kmcp.dev/description: MCP server built with fastmcp-python
    kmcp.dev/project-name: text-normalizer-mcp2
  labels:
    app.kubernetes.io/component: mcp-server
    app.kubernetes.io/instance: text-normalizer-mcp2
    app.kubernetes.io/managed-by: kmcp
    app.kubernetes.io/name: text-normalizer-mcp2
    app.kubernetes.io/part-of: kmcp
    kmcp.dev/framework: fastmcp-python
    kmcp.dev/version: 0.1.0
  name: text-normalizer-mcp2
  namespace: kagent
spec:
  deployment:
    cmd: python
    args:
      - src/main.py
      - --transport
      - http
      - --host
      - 0.0.0.0
      - --port
      - "3000"
    image: ghcr.io/okruga/lab3-mcp-app:0.0.4
    imagePullPolicy: Always
    port: 3000
  httpTransport:
    path: /mcp
    targetPort: 3000
  transportType: http
